<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfraReportingSystem.Domain\InfraReportingSystem.Domain.csproj" />
    <ProjectReference Include="..\InfraReportingSystem.Shared\InfraReportingSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\AuditLogsScreen\" />
    <Folder Include="Repositories\Admin\AuditLogsScreen\" />
  </ItemGroup>

</Project>
